name: firedartextreme
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.0.1
homepage: https://github.com/codekaze/firedart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1
  grpc: ^3.0.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0

  # Firebase Packages
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  firebase_auth: ^3.3.6
  firebase_messaging: ^11.2.6

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.10.0
